version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ems-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ems_math
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_pass
    ports:
      - "5432:5432"
    volumes:
      - ems_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ems-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ems_redis_data:/data

volumes:
  ems_postgres_data:
  ems_redis_data:
  